name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          
          # Hier zwingen wir die Action, NUR den Header zu nehmen:
          base: "header"
          config_timezone: Europe/Berlin
          
          # PLUGIN 1: 3D Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # PLUGIN 2: Detaillierte Sprachen-Statistik
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
